### ISSUE TITLE
Error al cargar facturas

### ISSUE THREAD

**Issue by egasemi** [CiudadFutura/FactUploader-Mision#1]
Procedimiento: ejecutar el archivo Files2Server.exe ubicado en C:\Archivos de programa (x86)\MDSoluciones\FacturasHaciaWeb desde la sesión ADMINISTRADOR

Resultado esperado: el script debería cambiarle el nombre de los pdfs a un formato FAC_XXXXX.PDF y después subirlos a la web

Resultado obtenido: el script se ejecuta y se cierra inmediatamente sin cambiar el nombre de los pdfs ni subirlos a la web. Y tampoco da ningún error por consola.

Posible error: Evo cambió la forma de nomenclar las facturas. Antes las nombraba con el formato FACXXXXXXXXXXXX_XXXXXXXXXXXX.PDF y ahora es ~~FACTRLOR-C-XXXXXXXXXXXX_XXXXXXXXXXXXXX.PDF~~
FACTLOTR-C-XXXXXXXXXXXX_XXXXXXXXXXXXXX.PDF

**Comment by azacchino** [comment]
Emi, buenas. Ahi vi el codigo creo que es asi tal cual. El problema esta en esta linea

https://github.com/CiudadFutura/FactUploader-Mision/blob/f725f5bed1ff8f65ef27fc7bdb7a1a387022320d/Files2Server/Program.cs#L125

No teno un entorno windows para compilarlo. Si no es tan urgente damo unos dias. Si no, te muestro como arreglarlo y lo arreglas vos :-).

**Comment by egasemi** [comment]
No es mega urgente y yo tampoco tengo Windows jaja así que dale tranqui y avísame si necesitas ayuda
